//! Generated-code detection.
//!
//! Machine-generated files (protobuf stubs, sqlc query code, bindgen FFI
//! bindings, ORM schemas) are frequently checked into repositories, where they
//! dominate symbol counts and drown hand-written code in search results. This
//! module recognises them from their header banner so commands can filter them
//! out.
//!
//! ## Why a table of per-generator checks and not one pattern
//!
//! There is no cross-ecosystem convention. GitHub Linguist — the most complete
//! catalogue of this problem — carries ~71 separate predicates, each with its
//! own marker string and its own line window, because every generator invented
//! its own banner. Two examples of why a single loose pattern misfires: the
//! protobuf C++/Java/Python banner contains **two** spaces in
//! `compiler.  DO NOT EDIT!`, and the protobuf JavaScript banner is a different
//! string that only appears on line 6.
//!
//! The one near-standard is Go's, specified by `go generate`:
//!
//! ```text
//! ^// Code generated .* DO NOT EDIT\.$
//! ```
//!
//! It has spread well beyond Go (protoc-gen-go, protoc-gen-ts_proto, sqlc,
//! twirp), so it earns a general check — but anchored, not substring-matched,
//! since the anchors are what keep prose that merely *mentions* generated code
//! from matching.
//!
//! ## Detection is a heuristic, and deliberately conservative
//!
//! A generator that writes no banner (rust-bindgen records only its own version;
//! cbindgen writes nothing by default) is undetectable from content alone, and a
//! file's provenance often lives in the build system rather than the file. This
//! module therefore under-reports rather than over-reports: filtering on it may
//! leave some generated files in the results, but it should not hide
//! hand-written code.

use std::path::Path;

/// How many leading lines are examined. Generators put their banner at the very
/// top; 40 lines matches the widest window any checked generator needs (Go's,
/// which allows a build-tag block and a license header above the marker).
const HEAD_LINES: usize = 40;

/// Cap on bytes read from a file when probing for a banner. Enough for 40 lines
/// of any realistic header, and bounds the cost on a minified or single-line
/// file whose "first 40 lines" could otherwise be megabytes.
const HEAD_BYTES: usize = 8 * 1024;

/// A recognised generated-code banner.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedMarker {
    /// Which generator family the banner identifies. Free-form label meant for
    /// display, not for matching on.
    pub tool: &'static str,
    /// The source artifact the generator recorded, when it recorded one.
    ///
    /// Only the protoc family and sqlc write this (`// source: path/to.proto`).
    /// The path is **relative to the generator's import root**, not to the
    /// repository, so consumers must suffix-match it against repo paths rather
    /// than compare for equality.
    pub source: Option<String>,
}

/// Detect a generated-code banner in the head of a file's contents.
///
/// `content` may be the whole file; only the first [`HEAD_LINES`] lines are
/// examined.
pub fn detect_generated(content: &str) -> Option<GeneratedMarker> {
    let lines: Vec<&str> = content.lines().take(HEAD_LINES).collect();

    let tool = detect_tool(&lines)?;
    Some(GeneratedMarker {
        tool,
        source: extract_source(&lines),
    })
}

fn detect_tool(lines: &[&str]) -> Option<&'static str> {
    // The Go convention, anchored per its spec. Also matches protoc-gen-go,
    // protoc-gen-ts_proto, sqlc and twirp. `#` covers the generators that
    // copied the convention into hash-comment languages.
    for line in lines {
        let t = line.trim();
        for leader in ["// ", "# ", "-- "] {
            if let Some(rest) = t.strip_prefix(leader) {
                if rest.starts_with("Code generated ") && rest.ends_with(" DO NOT EDIT.") {
                    return Some("code-generated-banner");
                }
            }
        }
    }

    // protoc, C++ / Java / Python / PHP / Objective-C backends. NB the double
    // space before `DO NOT EDIT!` is in protoc's own source; matching it
    // loosely would be wrong for no benefit.
    if lines
        .iter()
        .take(3)
        .any(|l| l.contains("Generated by the protocol buffer compiler.  DO NOT EDIT!"))
    {
        return Some("protoc");
    }

    // protoc, JavaScript backend — different string, and it sits below a
    // fixed preamble rather than at the top.
    if lines
        .iter()
        .take(8)
        .any(|l| l.contains("GENERATED CODE -- DO NOT EDIT!"))
    {
        return Some("protoc-js");
    }

    if lines
        .iter()
        .take(6)
        .any(|l| l.contains("Autogenerated by Thrift Compiler"))
    {
        return Some("thrift");
    }

    // javah / javac -h JNI headers: exact first line, plus the jni.h include
    // right below it, which is what separates it from a hand-written file that
    // happens to open with a "do not edit" plea.
    if lines
        .first()
        .is_some_and(|l| l.trim() == "/* DO NOT EDIT THIS FILE - it is machine generated */")
        && lines.iter().take(3).any(|l| l.contains("#include <jni.h>"))
    {
        return Some("javah");
    }

    for (needle, tool) in [
        ("automatically generated by rust-bindgen", "rust-bindgen"),
        ("@generated automatically by Diesel CLI", "diesel-cli"),
        ("auto generated by OpenAPI Generator", "openapi-generator"),
        ("Code generated by Prisma", "prisma"),
        (
            "Generated by the gRPC Python protocol compiler plugin",
            "grpc-python",
        ),
    ] {
        if lines.iter().take(10).any(|l| l.contains(needle)) {
            return Some(tool);
        }
    }

    // The Phabricator/Meta `@generated` annotation, widely reused by JS
    // tooling. Narrow window: this one is a bare token rather than a sentence,
    // so it is the most likely of the set to appear incidentally in prose.
    if lines.iter().take(5).any(|l| {
        let t = l.trim();
        t.contains("@generated")
            && (t.starts_with("//") || t.starts_with("*") || t.starts_with("#"))
    }) {
        return Some("generated-annotation");
    }

    None
}

/// Pull the `source:` provenance line the protoc family and sqlc emit.
fn extract_source(lines: &[&str]) -> Option<String> {
    for line in lines.iter().take(10) {
        let t = line.trim();
        for leader in ["// ", "# ", "-- "] {
            if let Some(rest) = t.strip_prefix(leader) {
                if let Some(path) = rest.strip_prefix("source: ") {
                    let path = path.trim();
                    if !path.is_empty() {
                        return Some(path.to_string());
                    }
                }
            }
        }
    }
    None
}

/// Detect a generated-code banner by reading the head of `path`.
///
/// Reads at most [`HEAD_BYTES`]. Returns `false` for unreadable files and for
/// content that is not valid UTF-8 up to the read boundary — an unreadable file
/// is not evidence of generation, and this predicate is used to *hide* results,
/// so it must fail towards keeping them.
pub fn is_generated_file(path: &Path) -> bool {
    let Some(head) = read_head(path) else {
        return false;
    };
    detect_generated(&head).is_some()
}

fn read_head(path: &Path) -> Option<String> {
    use std::io::Read;

    let mut file = std::fs::File::open(path).ok()?;
    let mut buf = vec![0u8; HEAD_BYTES];
    let n = file.read(&mut buf).ok()?;
    buf.truncate(n);
    // A truncated read can split a multi-byte char; keep the valid prefix.
    match String::from_utf8(buf) {
        Ok(s) => Some(s),
        Err(e) => {
            let valid = e.utf8_error().valid_up_to();
            String::from_utf8(e.into_bytes()[..valid].to_vec()).ok()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognises_the_go_convention_and_keeps_the_source_path() {
        let src = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\
                   // versions:\n\
                   // \tprotoc-gen-go v1.36.11\n\
                   // \tprotoc        v5.27.1\n\
                   // source: grpc/health/v1/health.proto\n\n\
                   package grpc_health_v1\n";
        let m = detect_generated(src).expect("banner");
        assert_eq!(m.tool, "code-generated-banner");
        assert_eq!(m.source.as_deref(), Some("grpc/health/v1/health.proto"));
    }

    #[test]
    fn recognises_sqlc_and_hash_comment_generators() {
        let go = "// Code generated by sqlc. DO NOT EDIT.\n// versions:\n// sqlc v1.27.0\n// source: query.sql\n";
        let m = detect_generated(go).expect("sqlc banner");
        assert_eq!(m.source.as_deref(), Some("query.sql"));

        let py = "# Code generated by some-tool. DO NOT EDIT.\n";
        assert!(detect_generated(py).is_some());
    }

    #[test]
    fn recognises_the_protoc_banner_with_its_double_space() {
        let src = "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n\
                   // NO CHECKED-IN PROTOBUF GENCODE\n\
                   // source: example.proto\n";
        let m = detect_generated(src).expect("protoc banner");
        assert_eq!(m.tool, "protoc");
        assert_eq!(m.source.as_deref(), Some("example.proto"));

        // Single space is a different string and must not match this arm.
        let single = "// Generated by the protocol buffer compiler. DO NOT EDIT!\n";
        assert_eq!(detect_generated(single), None);
    }

    #[test]
    fn recognises_javah_only_with_the_jni_include() {
        let real = "/* DO NOT EDIT THIS FILE - it is machine generated */\n#include <jni.h>\n";
        assert_eq!(detect_generated(real).map(|m| m.tool), Some("javah"));

        // Same plea, no jni.h — a hand-written vendored file, not a JNI header.
        let plea = "/* DO NOT EDIT THIS FILE - it is machine generated */\nint main(void) {}\n";
        assert_eq!(detect_generated(plea), None);
    }

    #[test]
    fn recognises_the_remaining_generator_banners() {
        for (src, tool) in [
            ("/* automatically generated by rust-bindgen 0.69.4 */\n", "rust-bindgen"),
            ("// @generated automatically by Diesel CLI.\n", "diesel-cli"),
            (
                "/**\n * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).\n */\n",
                "openapi-generator",
            ),
            ("// Autogenerated by Thrift Compiler (0.19.0)\n", "thrift"),
        ] {
            assert_eq!(
                detect_generated(src).map(|m| m.tool),
                Some(tool),
                "failed to recognise {tool}"
            );
        }
    }

    #[test]
    fn does_not_flag_hand_written_code_that_talks_about_generated_code() {
        // Prose and doc comments discussing codegen must not be filtered away —
        // this is the false-positive direction that would hide real code.
        let cases = [
            "// This module post-processes code generated by protoc.\n",
            "//! Do not edit generated files by hand; re-run the generator.\n",
            "# The build step writes code generated from the schema.\n",
            "fn main() { println!(\"Code generated\"); }\n",
            "",
        ];
        for src in cases {
            assert_eq!(detect_generated(src), None, "false positive on: {src:?}");
        }
    }

    #[test]
    fn banner_below_a_license_header_is_still_found_but_not_below_the_window() {
        let mut src = String::new();
        for _ in 0..20 {
            src.push_str("// Copyright (c) 2026 Example Corp.\n");
        }
        src.push_str("// Code generated by protoc-gen-go. DO NOT EDIT.\n");
        assert!(detect_generated(&src).is_some());

        let mut deep = String::new();
        for _ in 0..HEAD_LINES {
            deep.push_str("// filler\n");
        }
        deep.push_str("// Code generated by protoc-gen-go. DO NOT EDIT.\n");
        assert_eq!(detect_generated(&deep), None, "window must be bounded");
    }

    #[test]
    fn source_is_none_when_the_generator_records_no_provenance() {
        let src = "/* automatically generated by rust-bindgen 0.69.4 */\n";
        assert_eq!(detect_generated(src).and_then(|m| m.source), None);
    }

    #[test]
    fn is_generated_file_reads_the_head_and_fails_towards_keeping_results() {
        let dir = tempfile::tempdir().expect("tempdir");
        let gen = dir.path().join("api.pb.go");
        std::fs::write(
            &gen,
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
        )
        .expect("write");
        assert!(is_generated_file(&gen));

        let hand = dir.path().join("main.go");
        std::fs::write(&hand, "package main\n\nfunc main() {}\n").expect("write");
        assert!(!is_generated_file(&hand));

        // Missing file: not evidence of generation.
        assert!(!is_generated_file(&dir.path().join("nope.go")));
    }
}
