//! CLI-level tests for `vex search --exclude-generated`.
//!
//! The filter reads each candidate file's header banner rather than answering
//! from the index, so these drive the real binary end to end: a hand-written
//! file and a generated one both define a symbol matching the query, and the
//! flag must drop exactly the generated one.

use std::path::Path;

use assert_cmd::Command;
use tempfile::TempDir;

fn vex_in(dir: &Path) -> Command {
    let mut cmd = Command::cargo_bin("vex").unwrap();
    cmd.current_dir(dir);
    cmd.env("VEX_CACHE_DIR", dir.join(".vex-test-cache"));
    cmd
}

/// Two Go files defining similarly-named symbols: one hand-written, one
/// carrying protoc-gen-go's banner.
fn setup(dir: &Path) {
    std::fs::write(dir.join(".vex.toml"), "local_cache = true\n").unwrap();
    std::fs::write(
        dir.join("handler.go"),
        "package api\n\nfunc InvoiceHandler() {}\n",
    )
    .unwrap();
    std::fs::write(
        dir.join("invoice.pb.go"),
        "// Code generated by protoc-gen-go. DO NOT EDIT.\n\
         // versions:\n\
         // \tprotoc-gen-go v1.36.11\n\
         // source: api/invoice.proto\n\n\
         package api\n\n\
         func InvoiceMessage() {}\n",
    )
    .unwrap();
}

#[test]
fn exclude_generated_drops_only_the_generated_file() {
    let tmp = TempDir::new().unwrap();
    setup(tmp.path());

    vex_in(tmp.path())
        .args(["index", "--path", "."])
        .assert()
        .success();

    // Baseline: both symbols are indexed and findable.
    let out = vex_in(tmp.path())
        .args(["search", "Invoice", "--limit", "20"])
        .assert()
        .success();
    let baseline = String::from_utf8_lossy(&out.get_output().stdout).to_string();
    assert!(
        baseline.contains("InvoiceHandler"),
        "hand-written symbol missing from baseline: {baseline}"
    );
    assert!(
        baseline.contains("InvoiceMessage"),
        "generated symbol missing from baseline: {baseline}"
    );

    // Filtered: the generated file's symbol is gone, the hand-written one stays.
    let out = vex_in(tmp.path())
        .args(["search", "Invoice", "--limit", "20", "--exclude-generated"])
        .assert()
        .success();
    let filtered = String::from_utf8_lossy(&out.get_output().stdout).to_string();
    assert!(
        filtered.contains("InvoiceHandler"),
        "hand-written symbol must survive the filter: {filtered}"
    );
    assert!(
        !filtered.contains("invoice.pb.go"),
        "generated file must not appear: {filtered}"
    );
}

/// The filter runs before `take(limit)`, so a limited search must still return
/// a full page of hand-written results even when generated files outrank them.
/// A regression that moved `take(limit)` ahead of the filter would silently
/// return fewer rows than asked for — the exact trap the over-fetch logic in
/// `cmd_search` exists to avoid.
#[test]
fn limit_is_filled_with_hand_written_results_despite_generated_ones() {
    let tmp = TempDir::new().unwrap();
    std::fs::write(tmp.path().join(".vex.toml"), "local_cache = true\n").unwrap();

    for i in 0..4 {
        std::fs::write(
            tmp.path().join(format!("handler{i}.go")),
            format!("package api\n\nfunc InvoiceHandler{i}() {{}}\n"),
        )
        .unwrap();
        std::fs::write(
            tmp.path().join(format!("invoice{i}.pb.go")),
            format!(
                "// Code generated by protoc-gen-go. DO NOT EDIT.\n\
                 // source: api/invoice.proto\n\n\
                 package api\n\n\
                 func InvoiceMessage{i}() {{}}\n"
            ),
        )
        .unwrap();
    }

    vex_in(tmp.path())
        .args(["index", "--path", "."])
        .assert()
        .success();

    let out = vex_in(tmp.path())
        .args([
            "search",
            "Invoice",
            "--limit",
            "3",
            "--exclude-generated",
            "--format",
            "compact",
        ])
        .assert()
        .success();
    let stdout = String::from_utf8_lossy(&out.get_output().stdout).to_string();

    let hits = stdout
        .lines()
        .filter(|l| l.contains("InvoiceHandler"))
        .count();
    assert_eq!(
        hits, 3,
        "limit must be filled from hand-written files, got {hits}: {stdout}"
    );
    assert!(
        !stdout.contains(".pb.go"),
        "no generated file may appear: {stdout}"
    );
}

/// A query whose every hit is generated must say so rather than looking like a
/// query that matched nothing.
#[test]
fn suppressing_every_result_explains_itself() {
    let tmp = TempDir::new().unwrap();
    std::fs::write(tmp.path().join(".vex.toml"), "local_cache = true\n").unwrap();
    std::fs::write(
        tmp.path().join("only.pb.go"),
        "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n\nfunc OnlyGenerated() {}\n",
    )
    .unwrap();

    vex_in(tmp.path())
        .args(["index", "--path", "."])
        .assert()
        .success();

    // Exit 1 is vex's established "no results" signal, not a failure — the
    // point of this test is the stderr note that explains WHY there are none.
    let out = vex_in(tmp.path())
        .args(["search", "OnlyGenerated", "--exclude-generated"])
        .assert()
        .code(1);
    let stderr = String::from_utf8_lossy(&out.get_output().stderr).to_string();
    assert!(
        stderr.contains("suppressed by --exclude-generated"),
        "empty result set must name the filter that emptied it; stderr: {stderr}"
    );
}

#[test]
fn exclude_generated_is_opt_in_and_off_by_default() {
    let tmp = TempDir::new().unwrap();
    setup(tmp.path());

    vex_in(tmp.path())
        .args(["index", "--path", "."])
        .assert()
        .success();

    let out = vex_in(tmp.path())
        .args(["search", "Invoice", "--limit", "20"])
        .assert()
        .success();
    let stdout = String::from_utf8_lossy(&out.get_output().stdout).to_string();
    assert!(
        stdout.contains("invoice.pb.go"),
        "default behaviour must not filter generated files: {stdout}"
    );
}
