//! CLI-level tests for `vex search --exclude-generated`.
//!
//! The filter reads each candidate file's header banner rather than answering
//! from the index, so these drive the real binary end to end: a hand-written
//! file and a generated one both define a symbol matching the query, and the
//! flag must drop exactly the generated one.

use std::path::Path;

use assert_cmd::Command;
use tempfile::TempDir;

fn vex_in(dir: &Path) -> Command {
    let mut cmd = Command::cargo_bin("vex").unwrap();
    cmd.current_dir(dir);
    cmd.env("VEX_CACHE_DIR", dir.join(".vex-test-cache"));
    cmd
}

/// Two Go files defining similarly-named symbols: one hand-written, one
/// carrying protoc-gen-go's banner.
fn setup(dir: &Path) {
    std::fs::write(dir.join(".vex.toml"), "local_cache = true\n").unwrap();
    std::fs::write(
        dir.join("handler.go"),
        "package api\n\nfunc InvoiceHandler() {}\n",
    )
    .unwrap();
    std::fs::write(
        dir.join("invoice.pb.go"),
        "// Code generated by protoc-gen-go. DO NOT EDIT.\n\
         // versions:\n\
         // \tprotoc-gen-go v1.36.11\n\
         // source: api/invoice.proto\n\n\
         package api\n\n\
         func InvoiceMessage() {}\n",
    )
    .unwrap();
}

#[test]
fn exclude_generated_drops_only_the_generated_file() {
    let tmp = TempDir::new().unwrap();
    setup(tmp.path());

    vex_in(tmp.path())
        .args(["index", "--path", "."])
        .assert()
        .success();

    // Baseline: both symbols are indexed and findable.
    let out = vex_in(tmp.path())
        .args(["search", "Invoice", "--limit", "20"])
        .assert()
        .success();
    let baseline = String::from_utf8_lossy(&out.get_output().stdout).to_string();
    assert!(
        baseline.contains("InvoiceHandler"),
        "hand-written symbol missing from baseline: {baseline}"
    );
    assert!(
        baseline.contains("InvoiceMessage"),
        "generated symbol missing from baseline: {baseline}"
    );

    // Filtered: the generated file's symbol is gone, the hand-written one stays.
    let out = vex_in(tmp.path())
        .args(["search", "Invoice", "--limit", "20", "--exclude-generated"])
        .assert()
        .success();
    let filtered = String::from_utf8_lossy(&out.get_output().stdout).to_string();
    assert!(
        filtered.contains("InvoiceHandler"),
        "hand-written symbol must survive the filter: {filtered}"
    );
    assert!(
        !filtered.contains("invoice.pb.go"),
        "generated file must not appear: {filtered}"
    );
}

#[test]
fn exclude_generated_is_opt_in_and_off_by_default() {
    let tmp = TempDir::new().unwrap();
    setup(tmp.path());

    vex_in(tmp.path())
        .args(["index", "--path", "."])
        .assert()
        .success();

    let out = vex_in(tmp.path())
        .args(["search", "Invoice", "--limit", "20"])
        .assert()
        .success();
    let stdout = String::from_utf8_lossy(&out.get_output().stdout).to_string();
    assert!(
        stdout.contains("invoice.pb.go"),
        "default behaviour must not filter generated files: {stdout}"
    );
}
